# Copyright (C) 2018  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

FROM arm32v7/ubuntu:18.04
MAINTAINER Christian Berger "christian.berger@gu.se"

# Set the env variable DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

ENV QEMU_EXECVE 1
COPY ./cross-build/cross-build-start /usr/bin/cross-build-start
COPY ./cross-build/cross-build-end /usr/bin/cross-build-end
COPY ./cross-build/qemu-arm-static /usr/bin/qemu-arm-static
COPY ./cross-build/sh-shim /usr/bin/sh-shim

RUN ["cross-build-start"]

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        software-properties-common && \
    add-apt-repository ppa:chrberger/libcluon && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        pkg-config \
        python-protobuf \
        python-sysv-ipc \
        python-numpy \
        python3-opencv \
        protobuf-compiler \
        libcluon \
        libgtk-3-dev \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libv4l-dev \
        libxvidcore-dev \
        libx264-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        gfortran \
        openexr \
        python3-dev \
        python3-numpy \
        libtbb2 \
        libtbb-dev \
        libdc1394-22-dev && \
    apt-get clean

RUN mkdir -p /tmp/opencv_build
RUN cd /tmp/opencv_build && git clone https://github.com/opencv/opencv.git && cd opencv && git checkout 3.4.2 && cd ..
RUN cd /tmp/opencv_build && git clone https://github.com/opencv/opencv_contrib.git && cd opencv_contrib && git checkout 3.4.2 && cd ..

RUN cd /tmp/opencv_build/opencv && \
    mkdir build && cd build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D INSTALL_C_EXAMPLES=OFF \
        -D INSTALL_PYTHON_EXAMPLES=OFF \
        -D OPENCV_EXTRA_MODULES_PATH=/tmp/opencv_build/opencv_contrib/modules \
        -D BUILD_EXAMPLES=OFF ..

RUN cd /tmp/opencv_build/opencv/build && make -j4 && make install && pkg-config --modversion opencv

RUN ["cross-build-end"]


FROM arm32v7/ubuntu:18.04 as deployer
MAINTAINER Christian Berger "christian.berger@gu.se"

# Set the env variable DEBIAN_FRONTEND to noninteractive
ENV DEBIAN_FRONTEND noninteractive

ENV QEMU_EXECVE 1
COPY ./cross-build/cross-build-start /usr/bin/cross-build-start
COPY ./cross-build/cross-build-end /usr/bin/cross-build-end
COPY ./cross-build/qemu-arm-static /usr/bin/qemu-arm-static
COPY ./cross-build/sh-shim /usr/bin/sh-shim

RUN ["cross-build-start"]

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        software-properties-common && \
    add-apt-repository ppa:chrberger/libcluon && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get dist-upgrade -y && \
    apt-get install -y --no-install-recommends \
        make \
        python3-protobuf \
        python3-sysv-ipc \
        python3-opencv \
        protobuf-compiler \
        libcluon \
        python3 \
        python3-numpy && \
    apt-get clean

WORKDIR /usr/local
COPY --from=0 /usr/local/ .

ADD . /opt/sources
WORKDIR /opt/sources
RUN make

RUN ["cross-build-end"]

ENTRYPOINT ["/opt/sources/myApplication_for_Python3.py"]

