version: '2'

services:
  control:
    image: kiwi-control
    build:
      context: .
      dockerfile: Dockerfile.amd64
    network_mode: "host"
    ipc: "host"
    volumes:
      - /tmp:/tmp
    command: "--cid=111 --freq=10 --verbose"
