# Copyright (C) 2020 Ola Benderius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

version: '2'

services:
  video-h264-replay-amd64:
    build:
      context: https://github.com/chalmers-revere/opendlv-video-h264-replay.git#v0.0.1
      dockerfile: Dockerfile.amd64
    restart: on-failure
    network_mode: "host"
    ipc: "host"
    volumes:
      - ~/kiwi-recordings:/opt/recordings
      - /tmp:/tmp
    environment:
      - DISPLAY=${DISPLAY}
    command: "--cid=111 --verbose --name=img.argb /opt/recordings/yourFile.rec" # Change the filename here, the path should stay the same

  vehicle-view:
    image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
    restart: on-failure
    network_mode: host
    volumes:
      - ~/recordings:/opt/vehicle-view/recordings 
      - /var/run/docker.sock:/var/run/docker.sock
